TST: Mark test_simple1 as a known V6 failure
This surfaced once V6 was added to the Travis matrix.

    File "/home/travis/build/datalad/datalad-crawler/datalad_crawler/dbs/base.py", line 86, in save
      with open(self._filepath, 'w') as f:
  IOError: [Errno 13] Permission denied: '[...]/.datalad/crawl/statuses/incoming.json'

All remaining known_failure_v6's are now due to this same issue.